---
title: "p3"
output: github_document
date: "2024-12-03"
---

```{r include=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(p8105.datasets)
library(modelr)
library(mgcv)
library(SemiPar)
library(ggridges)
library(patchwork)
library(forcats)
library(modelr) 
library(mgcv)

#R figure settings
knitr::opts_chunk$set(
  fig.width = 9,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
bwt_data = read_csv("./data/birthweight.csv", na=c(" ",".","")) |>
  janitor::clean_names() |>
  drop_na() |>
  mutate(
    babysex = as.factor(babysex),
    malform = as.factor(malform),
    frace = as.factor(frace),
    mrace = as.factor(mrace)
  )
#str(bwt_data)

```

```{r}
#model 1
#nested model process of selecting variables 
simple_model_1 = lm(bwt ~ babysex + bhead + blength, data = bwt_data) #baby's variables

full_model_1 = lm(bwt ~ babysex + bhead + blength+ delwt + fincome + frace + gaweeks + malform +
              mrace + pnumlbw + smoken + wtgain, data = bwt_data) 

anova(simple_model_1, full_model_1)|>
  broom::tidy() #p-value less than 0.05 

bwt_data = bwt_data |>
  add_predictions(full_model_1) |> #pred
  add_residuals(full_model_1) #resid

bwt_data |> 
  ggplot(aes(x = pred, y = resid)) +
  geom_point() +
  labs(
    title = "Predictions vs Residuals",
    x = "Predictions",
    y = "Residuals"
  ) 

```

```{r}
#main effects
model_2 = lm(bwt ~  blength + gaweeks, data = bwt_data)
model_2 |> 
  broom::tidy() |>
  select(term, estimate, p.value) 

#main effects + interactions
model_3 = lm(bwt ~ bhead * blength * babysex, data = bwt_data)

model_3 |> 
  broom::tidy() |>
  select(term, estimate, p.value) 
```


```{r}
cv_df = crossv_mc(bwt_data, 5)
cv_df =
  cv_df |>
  mutate(
    full_model_1_b  = map(train, \(df) lm(bwt ~ babysex + bhead + blength+ delwt + fincome + frace + gaweeks + malform +
              mrace + pnumlbw + smoken + wtgain, data = df)),
    model_2_b  = map(train, \(df) lm(bwt ~  blength + gaweeks, data = df)),
    model_3_b  = map(train, \(df) lm(bwt ~ bhead * blength * babysex, data = df))) |>
  mutate(
    rmse_full_model = map2_dbl(full_model_1_b, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_mode_l2 = map2_dbl(model_2_b, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_model_3 = map2_dbl(model_3_b, test, \(mod, df) rmse(model = mod, data = df)))


cv_df |>
  select(starts_with("rmse")) |>
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_") |>
  mutate(model = fct_inorder(model)) |>
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```


```{r}
#Make this comparison in terms of the cross-validated prediction error; use crossv_mc and functions in purrr as appropriate.
cv_df =
  crossv_mc(lidar_df, 100)

cv_df |> pull(train) |> nth(1) |> as_tibble()

cv_df =
  cv_df |>
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))


cv_df |>
  select(starts_with("rmse")) |>
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_") |>
  mutate(model = fct_inorder(model)) |>
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

