---
title: "p8105_hw6_lk2776"
output: html_document
date: "2024-12-02"
---

```{r}
library(tidyverse)
library(ggplot2)
library(p8105.datasets)
library(modelr)
library(mgcv)
library(SemiPar)
library(ggridges)
library(patchwork)
library(forcats)

#R figure settings
knitr::opts_chunk$set(
  fig.width = 9,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
#problem2
data = read_csv("./data/homicide-data.csv", na=c("Unknown",".",""), ) |>
  janitor::clean_names() |>
  drop_na() |>
  mutate(city_state = paste(city, state, sep="_"), 
         status = if_else(
           disposition %in% c("Closed without arrest", "Open/No arrest"), "1", "0")) |>
 filter(!city_state %in% c("Tulsa_AL","Dallas_TX","Phoenix_AZ","Kansas City_MO")) |>
  filter(victim_race %in% c("White","Black")) |>
  mutate(victim_age = as.numeric(victim_age), 
         status = as.numeric(status))

```

```{r}
#baltimore logistic
baltimore_data = data |>
  filter(city_state == "Baltimore_MD") 

fit_logistic =
  baltimore_data |>
  glm(status ~ victim_age + victim_race + victim_sex, data = _, family = binomial()) |>
  broom::tidy(conf.int=TRUE) |>
  mutate(log_OR = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high)) |>
  select(term, OR = estimate, log_OR, conf.low,conf.high,p.value) |>
  filter(term == "victim_sexMale")
  
#fit_logistic |> knitr::kable()

```


```{r}
#all cities - fit logistic
all_cities_fit_logistic = data |> 
  group_by(city_state) |>
  nest() |>
  mutate(models = map(data, \(df) glm(status ~ victim_age + victim_race + victim_sex, data = df, family = binomial())),
  results = map(models, broom::tidy,conf.int=TRUE)) |>
  select(-data, -models) |>
  unnest(results) |>
  mutate(log_OR = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high)) |>
  select(term, OR = estimate, log_OR, conf.low,conf.high,p.value) |>
  filter(term == "victim_sexMale") 

#all_cities_fit_logistic |> knitr::kable()
  
```

The below plot shows 
```{r}

all_cities_fit_logistic |>
 # mutate(city_state = fct_reorder(city_state,log_OR)) |> #not working
ggplot(aes(x= reorder(city_state,log_OR), y = log_OR)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 80, hjust
= 1))+
  labs(
    title = "Log OR across Cities, States",
    x = "City, State",
    y = "Log OR"
  )
  
```



```{r}


  map(glm(status ~ victim_age + victim_race + victim_sex, data = _, family = binomial()) 
      
      results = map(models, broom::tidy)) |>
  select(-data, -models) |>
  
models = map(data, \(df) lm(price ~ stars + room_
type, data = df)),

#all cities prop test
prop_results_all_cities = summary_data |>
  mutate(prop_test_out_all = map2(unsolved_homicides,total_number_of_homicides, \(x,y) prop.test(x,y)),
         tidy_df = map(prop_test_out_all,tidy))|>
  unnest(tidy_df) |>
  select(city_state,estimate,conf.low,conf.high)
```


```{r}
fit_logistic_ci = as_tibble(confint(fit_logistic, level = 0.95), rownames="term")

fit_logistic_all = fit_logistic |>
  broom::tidy() |> 
  left_join(fit_logistic_ci, by = "term")

fit_logistic_all |>
  #broom::tidy() |>
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, `2.5 %`,`97.5 %`, p.value) |>
  filter(term == "victim_sexMale") #|>
  #knitr::kable()

```



```{r}
baltimore_df =
  read_csv("data/homicide-data.csv") |>
  filter(city == "Baltimore") |>
  mutate(
    resolved = as.numeric(disposition == "Closed by a
rrest"),
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White")) |> 
  select(resolved, victim_age, victim_race, victim_sex)

fit_logistic =
  baltimore_df |>
  glm(resolved ~ victim_age + victim_race + victim_sex, data = _, family = binomial())

fit_logistic |>
  broom::tidy() |>
  mutate(OR = exp(estimate)) |>
  select(term, log_OR = estimate, OR, p.value) |>
  knitr::kable(digits = 3)

baltimore_df |>
  modelr::add_predictions(fit_logistic) |>
  mutate(fitted_prob = boot::inv.logit(pred))
```

